import { Translations } from './translations';

export const ar: Translations = {
    appName: "خدماتي",
    toggleNavigationMenu: "تبديل قائمة التنقل",
    dashboardMenu: "قائمة لوحة التحكم",
    dashboardMenuDesc: "روابط التنقل في لوحة التحكم.",
    tagline: "ابحث عن أفضل مقدمي الخدمات المحليين",
    home: "الرئيسية",
    services: "الخدمات",
    login: "تسجيل الدخول",
    register: "التسجيل",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    dashboard: "لوحة التحكم",
    language: "اللغة",
    theme: "النمط",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    searchPlaceholder: "ابحث عن مقدمي الخدمات بالاسم، الفئة...",
    search: "بحث",
    serviceProviders: "مقدمي الخدمات",
    serviceSeekers: "طالبي الخدمات",
    registerAs: "التسجيل كـ",
    provider: "مقدم خدمة",
    seeker: "طالب خدمة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم الكامل",
    realNameHelpText: "يرجى استخدام اسمك الحقيقي كما يظهر في المستندات البنكية.",
    bankNamePlaceholder: "مثال: جون دو",
    qualifications: "نبذة عني / السيرة الذاتية",
    phoneNumber: "رقم الهاتف",
    address: "العنوان / موقع الخدمة",
    serviceAreas: "مناطق الخدمة",
    serviceAreasPlaceholder: "مثال: وسط المدينة، الضواحي الشمالية (مفصولة بفاصلة)",
    category: "الفئة",
    plumbing: "السباكة",
    electrical: "الكهرباء",
    carpentry: "النجارة",
    painting: "الدهان",
    homeCleaning: "تنظيف المنازل",
    construction: "البناء",
    plastering: "الجبس",
    other: "خدمات أخرى",
    searchHistory: "سجل البحث",
    noResultsFound: "لم يتم العثور على نتائج.",
    loading: "جاري التحميل...",
    submit: "إرسال",
    viewDetails: "عرض التفاصيل",
    errorOccurred: "حدث خطأ.",
    welcomeTo: "أهلاً بك في",
    findSkilledArtisans: "ابحث عن فنيين مهرة لاحتياجاتك.",
    orPostYourServices: "أو انشر خدماتك ووصل إلى عملاء جدد.",
    getStarted: "ابدأ الآن",
    browseServices: "تصفح الخدمات",
    joinAsProvider: "انضم كمقدم خدمة",
    joinAsSeeker: "انضم كطالب خدمة",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    dontHaveAccount: "لا تملك حسابًا؟",
    createAccount: "إنشاء حساب",
    fillYourProfile: "أدخل تفاصيل ملفك الشخصي",
    serviceDetails: "تفاصيل الخدمة",
    contactInfo: "معلومات الاتصال",
    saveChanges: "حفظ التغييرات",
    profileUpdatedSuccessfully: "تم تحديث الملف الشخصي بنجاح!",
    selectCategory: "اختر الفئة",
    serviceCategory: "فئة الخدمة",
    searchByAddressOrKeyword: "ابحث بالعنوان أو الكلمة الرئيسية",
    recentSearches: "عمليات البحث الأخيرة",
    clearHistory: "مسح السجل",
    noHistoryYet: "ليس لديك سجل بحث بعد.",
    requiredField: "هذا الحقل مطلوب",
    invalidEmail: "عنوان بريد إلكتروني غير صالح",
    passwordTooShort: "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
    passwordsDoNotMatch: "كلمتا المرور غير متطابقتين",
    confirmPassword: "تأكيد كلمة المرور",
    emailVerificationSent: "تم إرسال رابط تفعيل الحساب",
    checkYourEmailForVerification: "تم إرسال رابط تفعيل إلى بريدك الإلكتروني. يرجى التحقق من بريدك (بما في ذلك مجلد البريد المزعج) لتفعيل حسابك.",
    contactUs: "اتصل بنا",
    adminDashboard: "لوحة تحكم المشرف",
    welcomeAdmin: "أهلاً بك أيها المشرف!",
    adminPlaceholder: "هذه لوحة تحكم المشرف. المزيد من الميزات قريباً.",
    selectService: "اختر الخدمة",
    hidePassword: "إخفاء كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    authServiceUnavailable: "خدمة المصادقة غير متوفرة حالياً. يرجى المحاولة مرة أخرى لاحقاً أو الاتصال بالدعم الفني.",
    serviceUnavailableTitle: "الخدمة غير متوفرة",
    serviceUnavailableMessage: "إحدى الخدمات الأساسية (مثل المصادقة أو قاعدة البيانات) غير مهيأة أو غير متوفرة حالياً. يرجى المحاولة مرة أخرى لاحقاً أو الاتصال بالدعم الفني.",
    coreServicesUnavailableDashboard: "الخدمات الأساسية غير متوفرة. لا يمكن تحميل لوحة التحكم في هذا الوقت. يرجى المحاولة مرة أخرى لاحقاً أو الاتصال بالدعم الفني.",
    loginSuccessful: "تم تسجيل الدخول بنجاح",
    welcomeBackUser: "أهلاً بعودتك، {userName}!",
    loginFailedGeneric: "فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد الخاصة بك.",
    invalidCredentials: "بريد إلكتروني أو كلمة مرور غير صالحين. يرجى المحاولة مرة أخرى.",
    networkError: "خطأ في الشبكة. يرجى التحقق من اتصالك بالإنترنت.",
    loginFailedTitle: "فشل تسجيل الدخول",
    registrationFailedGeneric: "فشل التسجيل. يرجى المحاولة مرة أخرى.",
    emailAlreadyInUse: "هذا البريد الإلكتروني مسجل بالفعل. يرجى تسجيل الدخول أو استخدام بريد إلكتروني آخر.",
    passwordTooWeak: "كلمة المرور ضعيفة جداً. يرجى اختيار كلمة مرور أقوى.",
    registrationFailedTitle: "فشل التسجيل",
    userNotAuthenticated: "المستخدم غير موثوق. يرجى تسجيل الدخول مرة أخرى.",
    userNotIdentified: "لم يتم تحديد المستخدم. يرجى تسجيل الدخول مرة أخرى.",
    coreServicesUnavailable: "الخدمات الأساسية غير جاهزة أو غير متوفرة.",
    providerInfoMissing: "معلومات مقدم الخدمة مفقودة. يرجى المحاولة مرة أخرى.",
    invalidDate: "تاريخ غير صالح",
    delete: "حذف",
    cancel: "إلغاء",
    welcome: "أهلاً بك!",
    completeYourProfile: "يرجى استكمال ملفك الشخصي كمقدم خدمة.",
    couldNotFetchProfile: "تعذر جلب بيانات الملف الشخصي.",
    authError: "خطأ في المصادقة",
    userNotAuthOrServiceUnavailable: "المستخدم غير موثوق أو الخدمة غير متوفرة.",
    profileChangesSaved: "تم حفظ تغييرات ملفك الشخصي.",
    failedUpdateProfile: "فشل تحديث الملف الشخصي.",
    profilePageDescription: "إدارة تفاصيل ملفك الشخصي كمقدم خدمة في {appName}.",
    profileEditingUnavailable: "تحرير الملف الشخصي غير متوفر حالياً لأن الخدمات الأساسية غير مهيأة.",
    profileHelpTextCategory: "اختر فئة خدمتك الرئيسية.",
    searchHistoryClearedTitle: "تم مسح سجل البحث",
    searchHistoryClearedSuccess: "تم مسح سجل البحث الخاص بك بنجاح.",
    searchHistoryPageDescription: "راجع عمليات البحث السابقة عن الخدمات.",
    confirmClearHistoryTitle: "هل أنت متأكد أنك تريد مسح سجل البحث الخاص بك؟",
    confirmClearHistoryDescription: "هذا الإجراء لا يمكن التراجع عنه. سيتم حذف جميع إدخالات سجل البحث بشكل دائم.",
    noHistoryYetDescription: "سجل البحث الخاص بك فارغ. ابدأ بالبحث عن الخدمات لكي تظهر هنا.",
    searchedOn: "تم البحث في:",
    repeatSearch: "تكرار البحث",
    failedLoadServices: "فشل تحميل الخدمات.",
    backButton: "رجوع",
    backToSearch: "العودة إلى البحث",
    postedOnFull: "انضم في:",
    serviceCategoriesTitle: "فئات الخدمة:",
    servesAreasTitle: "مناطق الخدمة",
    contactProvider: "تواصل مع {providerName}",
    providerDetailsNotAvailable: "تفاصيل مقدم الخدمة غير متوفرة.",
    searchServicesPageDescription: "ابحث عن فنيين مهرة من خلال الاسم، نوع الخدمة، أو الكلمات الرئيسية.",
    tryDifferentKeywords: "جرب البحث بكلمات رئيسية مختلفة أو تحقق من التهجئة.",
    noServicesAvailableYet: "لا يوجد مقدمو خدمات متاحون بعد",
    checkBackLater: "لا يوجد حالياً مقدمو خدمات مسجلون. تحقق مرة أخرى لاحقاً!",
    switchToDarkMode: "التبديل إلى الوضع الداكن",
    switchToLightMode: "التبديل إلى الوضع الفاتح",
    unauthorized: "غير مصرح به",
    loginAsAdmin: "يرجى تسجيل الدخول كمشرف.",
    accessDenied: "تم رفض الوصول",
    notAuthorizedViewPage: "أنت غير مصرح لك بعرض هذه الصفحة.",
    adminDashboardDescription: "إدارة المستخدمين، الخدمات، وإعدادات التطبيق.",
    paymentApprovalsDescription: "مراجعة واعتماد المدفوعات المعلقة.",
    reviewProviderVerifications: "مراجعة طلبات تفعيل مقدمي الخدمات.",
    disputeResolution: "حل النزاعات",
    disputeResolutionDescription: "مراجعة وحل نزاعات المستخدمين.",
    adminDashboardUnavailable: "لوحة تحكم المشرف غير متوفرة حالياً لأن الخدمات الأساسية غير مهيأة.",
    logoutFailed: "فشل تسجيل الخروج",
    goToHomepage: "الذهاب إلى الصفحة الرئيسية",
    redirectingToLogin: "جاري إعادة التوجيه إلى صفحة تسجيل الدخول...",
    verifyingUserRole: "جاري التحقق من دور المستخدم...",
    verifyEmailPromptTitle: "يرجى تفعيل عنوان بريدك الإلكتروني.",
    verifyEmailPromptMessage: "تم إرسال رابط تفعيل إلى {email}. تحقق من بريدك (بما في ذلك مجلد البريد المزعج).",
    resendVerificationEmail: "إعادة إرسال رابط التفعيل",
    verificationEmailResent: "تم إعادة إرسال رابط التفعيل",
    checkYourEmail: "يرجى التحقق من بريدك الإلكتروني.",
    errorResendingVerificationEmail: "تعذر إعادة إرسال رابط التفعيل.",
    welcomeToDashboardUser: "أهلاً بك في لوحة تحكمك، {userName}!",
    welcomeToDashboardProvider: "أهلاً بك في لوحة تحكم مقدم الخدمة!",
    welcomeToDashboardSeeker: "أهلاً بك في لوحة تحكم طالب الخدمة!",
    profileDescriptionProvider: "قم بتحديث معلوماتك الشخصية والخدمية.",
    searchDescriptionSeeker: "ابحث عن فنيين مهرة لاحتياجاتك.",
    searchHistoryDescriptionSeeker: "راجع عمليات البحث السابقة عن الخدمات.",
    dashboardTaglineProvider: "إدارة ملفك الشخصي والتواصل مع العملاء.",
    dashboardTaglineSeeker: "ابحث وقيّم أفضل الخدمات لاحتياجاتك.",
    dashboardBannerAlt: "لافتة لوحة التحكم مع أدوات أو صور مساحة عمل",
    contactPageTitle: "اتصل بنا",
    contactPageDescription: "لديك أسئلة أو ملاحظات؟ تواصل معنا!",
    yourName: "اسمك",
    yourEmail: "بريدك الإلكتروني",
    subject: "الموضوع",
    message: "الرسالة",
    sendMessage: "أرسل الرسالة",
    messageSentSuccessTitle: "تم إرسال الرسالة!",
    messageSentSuccessDescription: "شكراً لرسالتك. سنقوم بالرد عليك قريباً.",
    messageSentErrorTitle: "خطأ في إرسال الرسالة",
    messageSentErrorDescription: "عذراً، حدثت مشكلة أثناء إرسال رسالتك. يرجى المحاولة مرة أخرى لاحقاً.",
    contactFormIntro: "يسعدنا أن نسمع منك! يرجى ملء النموذج أدناه وسنتواصل معك في أقرب وقت ممكن.",
    formSubmitActivationNote: "ملاحظة: لكي يعمل هذا النموذج، يحتاج مالك mobusinessarena@gmail.com إلى تفعيله مرة واحدة عبر بريد إلكتروني من FormSubmit.co بعد أول محاولة إرسال.",
    tryAgain: "حاول مرة أخرى",
    backToDashboard: "العودة إلى لوحة التحكم",
    plumbingDescription: "خدمات سباكة متخصصة للإصلاحات، التركيبات، والصيانة.",
    electricalDescription: "حلول كهربائية آمنة وموثوقة لمنزلك وعملك.",
    carpentryDescription: "نجارة ماهرة للأثاث، الإصلاحات، والمشاريع المخصصة.",
    paintingDescription: "خدمات دهان احترافية لمظهر جديد ومنعش.",
    homeCleaningDescription: "خدمات تنظيف منازل موثوقة لمساحة معيشة نظيفة تمامًا.",
    constructionDescription: "خدمات بناء شاملة من الأساس حتى التشطيب.",
    plasteringDescription: "جبس عالي الجودة للجدران والأسقف الملساء والمتينة.",
    otherServicesDescription: "خدمات أخرى متنوعة لتلبية احتياجاتك الفريدة.",
    reviews: "التقييمات",
    averageRating: "متوسط التقييم",
    noReviewsYet: "لا توجد تقييمات بعد",
    rateThisProvider: "قيّم مقدم الخدمة هذا",
    rating: "تقييمك",
    comment: "تعليقك (اختياري)",
    submitRating: "إرسال التقييم",
    loginToRate: "يجب أن تكون مسجلاً للدخول لإرسال تقييم.",
    selectRating: "يرجى اختيار تقييم بالنجوم قبل الإرسال.",
    ratingSubmitted: "تم إرسال التقييم",
    thankYouForFeedback: "شكراً لملاحظاتك!",
    failedSubmitRating: "فشل إرسال التقييم.",
    providerNotFound: "لم يتم العثور على مقدم الخدمة.",
    providerIdMissing: "معرف مقدم الخدمة مفقود.",
    failedLoadProviderDetails: "فشل تحميل تفاصيل مقدم الخدمة.",
    firestoreIndexError: "فهرس Firestore مفقود. تحقق من إعدادات قاعدة البيانات الخاصة بك.",
    permissionDeniedError: "ليس لديك إذن لتنفيذ هذا الإجراء.",
    of: "من", // e.g. 4.5 of 5 stars
    viewProfile: "عرض الملف الشخصي",
    location: "الموقع",
    useCurrentLocation: "استخدام الموقع الحالي",
    locationSet: "تم تعيين الموقع بنجاح!",
    locationError: "فشل الحصول على الموقع. يرجى تفعيل خدمات الموقع.",
    findNearMe: "البحث عن خدمات بالقرب مني",
    findingLocation: "جاري البحث عن موقعك...",
    sortedByDistance: "مرتبة حسب المسافة",
    kmAway: "كم بعيداً",
    locationPermissionDenied: "تم رفض إذن الموقع. يرجى تفعيله في إعدادات المتصفح الخاص بك لاستخدام هذه الميزة.",
    locationNotSet: "لم يتم تعيين الموقع. يرجى تعيين موقعك لاستخدام هذه الميزة.",
    locationUnavailable: "خدمات الموقع غير متوفرة.",
    locationHelpText: "أدخل مدينة، حي، أو عنواناً محدداً.",
    forgotPassword: "هل نسيت كلمة المرور؟",
    forgotPasswordDescription: "أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.",
    sendResetLink: "إرسال رابط إعادة التعيين",
    resetLinkSentTitle: "تم إرسال رابط إعادة التعيين",
    resetLinkSentDescription: "تحقق من بريدك الإلكتروني للحصول على رابط إعادة تعيين كلمة المرور.",
    resetPasswordErrorTitle: "خطأ في إرسال رابط إعادة التعيين",
    userNotFound: "لم يتم العثور على مستخدم بهذا البريد الإلكتروني.",
    backToLogin: "العودة إلى صفحة تسجيل الدخول",
    settings: "الإعدادات",
    manageAccountSettings: "إدارة إعدادات حسابك.",
    dangerZone: "منطقة الخطر",
    dangerZoneDescription: "الإجراءات في هذا القسم لا يمكن التراجع عنها.",
    deleteAccount: "حذف الحساب",
    deleteAccountDescription: "حذف حسابك بشكل دائم وجميع البيانات المرتبطة به.",
    confirmDeleteAccountTitle: "تأكيد حذف الحساب",
    confirmDeleteAccountDescription: "هل أنت متأكد تماماً أنك تريد حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.",
    confirmDelete: "تأكيد الحذف",
    accountDeletedTitle: "تم حذف الحساب",
    accountDeletedSuccess: "تم حذف حسابك بنجاح. نأسف لمغادرتك!",
    accountDeletionFailed: "فشل حذف الحساب",
    accountDeletionError: "فشل حذف حسابك. يرجى المحاولة مرة أخرى أو الاتصال بالدعم الفني.",
    requiresRecentLoginError: "يجب أن تكون قد سجلت الدخول مؤخراً لتنفيذ هذا الإجراء. يرجى تسجيل الخروج ثم تسجيل الدخول مرة أخرى.",
    callNow: "اتصل الآن",
    contactOnWhatsApp: "تواصل عبر واتساب",
    aboutProvider: "عن {name}",
    specialties: "التخصصات",
    portfolioTitle: "معرض الأعمال",
    portfolioDescription: "اعرض أعمالك بالصور ومقاطع الفيديو.",
    mediaUploadDescription: "يمكنك تحميل ما يصل إلى 5 صور أو مقاطع فيديو (بحد أقصى 10 ميجابايت لكل منها).",
    uploadMedia: "تحميل وسائط",
    uploading: "جاري الرفع...",
    portfolioLimitReachedTitle: "تم الوصول إلى الحد الأقصى للملفات",
    portfolioLimitReachedDescription: "لقد وصلت إلى الحد الأقصى المسموح به وهو 5 ملفات في معرض أعمالك.",
    fileTooLargeTitle: "الملف كبير جداً",
    fileTooLargeDescription: "حجم الملف يتجاوز الحد الأقصى المسموح به وهو 10 ميجابايت. يرجى تحميل ملف أصغر.",
    unsupportedFileTypeTitle: "نوع الملف غير مدعوم",
    unsupportedFileTypeDescription: "نحن ندعم فقط صيغ JPG، PNG، و MP4.",
    fileUploadedSuccessTitle: "تم رفع الملف",
    fileUploadErrorTitle: "فشل الرفع",
    fileUploadErrorDescription: "حدث خطأ أثناء الرفع. يرجى المحاولة مرة أخرى.",
    storageUnauthorizedError: "غير مصرح لك برفع الملفات.",
    storageUnauthorizedDeleteError: "غير مصرح لك بحذف هذا الملف.",
    fileDeletedSuccessTitle: "تم حذف الملف",
    fileDeleteErrorTitle: "فشل الحذف",
    fileDeleteErrorDescription: "حدث خطأ أثناء حذف الملف. يرجى المحاولة مرة أخرى.",
    confirmDeleteFileTitle: "حذف الملف؟",
    confirmDeleteFileDescription: "هل أنت متأكد أنك تريد حذف هذا الملف؟ هذا الإجراء لا يمكن التراجع عنه.",
    noPortfolioItems: "لم يتم رفع أي ملفات في معرض الأعمال بعد.",
    fileNotFoundInStorage: "لم يتم العثور على الملف في التخزين.",
    imageRejectedTitle: "تم رفض الصورة",
    imageRejectedDescription: "تم رفض الصورة التي تم رفعها بسبب محتوى غير لائق. يرجى رفع صورة مناسبة.",
    videoRejectedTitle: "تم رفض الفيديو",
    videoRejectedDescription: "تم رفض الفيديو الذي تم رفعه بسبب محتوى غير لائق. يرجى رفع فيديو مناسب.",
    analyzingImageTitle: "جاري تحليل الصورة",
    analyzingImageDescription: "نحن نقوم بتحليل صورتك للتأكد من سلامتها وتوافقها مع المعايير.",
    analyzingVideoTitle: "جاري تحليل الفيديو",
    analyzingVideoDescription: "نحن نقوم بتحليل الفيديو الخاص بك للتأكد من سلامته وتوافقه مع المعايير. قد يستغرق هذا بعض الوقت.",
    images: "الصور",
    videos: "مقاطع الفيديو",
    portfolioImage: "صورة معرض الأعمال",
    portfolioVideo: "فيديو معرض الأعمال",
    fullscreenViewOf: "عرض بملء الشاشة لـ {title}",
    whatsappMessage: "أهلاً {providerName}، لقد رأيت ملفك الشخصي على {appName} وأود الاستفسار عن خدماتك.",
    aiAdGenerationTitle: "إنشاء إعلان بالذكاء الاصطناعي",
    aiAdGenerationDescription: "دع الذكاء الاصطناعي لدينا ينشئ لك إعلاناً جذاباً بناءً على ملفك الشخصي.",
    primaryService: "الخدمة الرئيسية",
    primaryServicePlaceholder: "مثال: كهربائي، سباك",
    serviceAreasPlaceholderAI: "مثال: وسط المدينة، الضواحي الشمالية",
    commaSeparated: "مفصولة بفاصلة",
    contactInfoOptional: "معلومات الاتصال (اختياري)",
    contactInfoPlaceholder: "مثال: رقم هاتفك أو بريدك الإلكتروني",
    keywordsOptional: "الكلمات الرئيسية (اختياري)",
    keywordsPlaceholder: "مثال: سريع، بأسعار معقولة، محترف",
    generateAd: "إنشاء الإعلان",
    reviewAiAd: "مراجعة إعلانك الذي أنشأه الذكاء الاصطناعي",
    reviewAiAdDescription: "راجع الإعلان الذي أنشأه الذكاء الاصطناعي. يمكنك تعديله قبل الإرسال.",
    adBody: "محتوى الإعلان",
    adImageRequired: "صورة الإعلان مطلوبة",
    backToEditInfo: "العودة لتعديل المعلومات",
    submitForApproval: "إرسال للموافقة",
    aiGenerationFailed: "فشل إنشاء الإعلان. يرجى المحاولة مرة أخرى.",
    validationError: "خطأ في التحقق",
    provideServiceType: "يرجى تقديم نوع الخدمة الرئيسي.",
    provideServiceArea: "يرجى تقديم منطقة خدمة واحدة على الأقل.",
    profileNameMissing: "اسم ملفك الشخصي مفقود. يرجى تحديث ملفك الشخصي.",
    imageRequiredForAd: "صورة مطلوبة لإنشاء إعلان.",
    adImageHint: "قم بتحميل صورة تمثل خدمتك.",
    createNewAd: "إنشاء إعلان جديد",
    chooseAdCreationMethod: "اختر كيفية إنشاء إعلانك:",
    createWithAi: "الإنشاء بالذكاء الاصطناعي",
    createWithAiDescription: "دع الذكاء الاصطناعي الخاص بنا ينشئ لك إعلاناً احترافياً بناءً على تفاصيل ملفك الشخصي.",
    createManually: "الإنشاء يدوياً",
    createManuallyDescription: "اكتب إعلانك بنفسك من البداية.",
    startNow: "ابدأ الآن",
    createAdManually: "إنشاء إعلان يدوياً",
    loginToSubmitAd: "يجب عليك تسجيل الدخول لإرسال إعلان.",
    adTitleTooShort: "عنوان الإعلان قصير جداً.",
    adTitleTooLong: "عنوان الإعلان طويل جداً.",
    adBodyTooShort: "محتوى الإعلان قصير جداً.",
    messages: "الرسائل",
    messageProvider: "مراسلة {providerName}",
    startChatError: "فشل بدء الدردشة. يرجى المحاولة مرة أخرى.",
    startConversation: "بدء محادثة",
    messageSent: "تم إرسال الرسالة!",
    conversations: "المحادثات",
    noConversations: "لا توجد محادثات بعد.",
    noConversationsDescription: "ابدأ محادثة مع مقدم خدمة أو طالب خدمة.",
    selectConversation: "اختر محادثة",
    selectConversationDescription: "اختر محادثة من القائمة اليسرى لعرض الرسائل.",
    typeYourMessage: "اكتب رسالتك...",
    loginToMessage: "يجب عليك تسجيل الدخول لإرسال رسالة.",
    you: "أنت",
    image: "صورة",
    video: "فيديو",
    audioRecordingNotSupported: "تسجيل الصوت غير مدعوم",
    audioRecordingNotSupportedDescription: "متصفحك لا يدعم تسجيل الصوت.",
    microphoneAccessDenied: "تم رفض الوصول إلى الميكروفون",
    microphoneAccessDeniedDescription: "يرجى تفعيل الوصول إلى الميكروفون في إعدادات متصفحك لتسجيل الصوت.",
    changePassword: "تغيير كلمة المرور",
    changePasswordDescription: "أرسل بريداً إلكترونياً لإعادة تعيين كلمة المرور.",
    sendResetEmail: "إرسال بريد إعادة التعيين",
    resetEmailSent: "تم إرسال بريد إعادة التعيين",
    resetEmailSentDescription: "تم إرسال بريد إلكتروني لإعادة تعيين كلمة المرور إلى عنوان بريدك الإلكتروني. يرجى التحقق من بريدك (بما في ذلك مجلد البريد المزعج) لتغيير كلمة المرور.",
    roleMissingTitle: "الدور مفقود",
    roleMissingDescription: "دور المستخدم غير محدد. يرجى تسجيل الدخول مرة أخرى.",
    profileNotFoundTitle: "لم يتم العثور على الملف الشخصي",
    profileNotFoundDescription: "لم يتم العثور على الملف الشخصي للمستخدم.",
    videoCall: "مكالمة فيديو",
    audioCall: "مكالمة صوتية",
    incomingCall: "مكالمة واردة",
    isCallingYou: "{userName} يتصل بك...",
    accept: "قبول",
    decline: "رفض",
    callFailed: "فشلت المكالمة",
    initiatingCall: "جاري بدء المكالمة...",
    callAccepted: "تم قبول المكالمة",
    callEnded: "انتهت المكالمة",
    callHasBeenTerminated: "تم إنهاء المكالمة.",
    connecting: "جاري الاتصال...",
    ringing: "جاري الرنين...",
    mediaAccessDeniedTitle: "تم رفض الوصول إلى الوسائط",
    mediaAccessDeniedDescription: "يرجى منح الوصول إلى الكاميرا والميكروفون في إعدادات المتصفح الخاص بك لإجراء المكالمات.",
    cameraAccessRequired: "الوصول إلى الكاميرا مطلوب لمكالمات الفيديو. يرجى تفعيله في إعدادات المتصفح الخاص بك.",
    enableVideoCalls: "تفعيل مكالمات الفيديو",
    enableVideoCallsDescription: "السماح للمستخدمين الآخرين بإجراء مكالمات فيديو معك.",
    missedCall: "مكالمة فائتة",
    callDeclined: "تم رفض المكالمة",
    callDuration: "مدة المكالمة",
    videoCallLog: "مكالمة فيديو",
    audioCallLog: "مكالمة صوتية",
    serviceAmount: "مبلغ الخدمة",
    enterServiceAmount: "أدخل إجمالي مبلغ الخدمة",
    platformCommission: "عمولة المنصة",
    providerPayout: "مدفوعات مقدم الخدمة",
    myOrders: "طلباتي",
    myOrdersDescriptionSeeker: "عرض حالة طلبات الخدمة والمدفوعات الخاصة بك.",
    myOrdersDescriptionProvider: "عرض حالة طلبات الخدمة وإدارة مدفوعاتك.",
    noOrdersYet: "لا توجد طلبات بعد.",
    noOrdersYetDescription: "لم تطلب أو تستلم أي خدمات بعد. ابدأ بالتصفح الآن!",
    pendingPayment: "بانتظار الدفع",
    paid: "تم الدفع",
    completed: "مكتمل",
    disputed: "متنازع عليه",
    resolved: "تم الحل",
    paymentApprovals: "اعتمادات الدفع",
    paymentRejectedTitle: "تم رفض إثبات الدفع",
    paymentRejectedMessage: "تم رفض إثبات الدفع لطلبك مع {userName}. يرجى رفع إثبات جديد.",
    paymentPendingTitle: "تم رفع إثبات الدفع",
    paymentPendingDescription: "تم رفع إثبات دفع بواسطة {userName} وهو بانتظار موافقتك.",
    paymentApprovedTitle: "تم اعتماد الدفع",
    paymentApprovedDescription: "لقد اعتمدت الدفع. يمكن لمقدم الخدمة الآن بدء الخدمة.",
    orderCompletedTitle: "تم اكتمال الطلب",
    orderCompletedMessage: "تم تحديد الطلب مع {userName} على أنه مكتمل. سيتم تحويل الأموال إلى مقدم الخدمة قريباً.",
    orderDisputedTitle: "تم رفع نزاع على الطلب",
    orderDisputedMessage: "تم رفع نزاع على طلبك مع {userName}.",
    orderDisputedDescription: "تم رفع نزاع. سيقوم فريق المشرفين لدينا بمراجعة الحالة والتواصل مع الطرفين.",
    approveManually: "اعتماد يدوياً",
    rejectManually: "رفض يدوياً",
    confirmRejectPaymentTitle: "هل أنت متأكد من أنك تريد رفض هذه الدفعة؟",
    confirmRejectPaymentDescription: "إذا رفضت هذه الدفعة، سيتم إشعار طالب الخدمة بتحميل إثبات جديد.",
    reject: "رفض",
    rejectionReason: "سبب الرفض (اختياري)",
    rejectionReasonPlaceholder: "مثال: صورة غير واضحة، مبلغ خاطئ...",
    rejectionFailedTitle: "فشل الرفض",
    rejectionSuccessTitle: "تم رفض الدفع",
    rejectionSuccessDescription: "تم إشعار طالب الخدمة بتحميل إثبات جديد.",
    requestService: "طلب خدمة",
    requestingServiceFrom: "طلب خدمة من {providerName}",
    serviceDescription: "وصف الخدمة",
    describeJobDetailPlaceholder: "صف المهمة بالتفصيل...",
    providerWillSeeDescription: "سيرى مقدم الخدمة هذا الوصف لفهم طلبك.",
    submitRequest: "إرسال الطلب",
    descriptionRequired: "وصف الخدمة مطلوب.",
    invalidAmount: "مبلغ غير صالح. يرجى إدخال رقم صحيح.",
    enterValidServiceAmount: "يرجى إدخال مبلغ خدمة صالح.",
    orderCreatedSuccessTitle: "تم إرسال طلب الخدمة",
    orderCreatedSuccessDescription: "تم إرسال طلب الخدمة الخاص بك إلى مقدم الخدمة. سيتم إشعارك بمجرد الموافقة عليه.",
    failedToCreateOrder: "فشل في إنشاء طلب الخدمة. يرجى المحاولة مرة أخرى.",
    loginToRequestService: "يجب عليك تسجيل الدخول لطلب خدمة.",
    backToProfile: "العودة إلى الملف الشخصي",
    pendingApproval: "بانتظار الموافقة",
    orderCreatedAwaitingApprovalDescription: "طلبك بانتظار موافقة مقدم الخدمة.",
    acceptOrder: "قبول الطلب",
    declineOrder: "رفض الطلب",
    orderAccepted: "تم قبول الطلب",
    orderDeclined: "تم رفض الطلب",
    orderAcceptedTitle: "تم قبول الطلب!",
    orderAcceptedMessage: "لقد قبل مقدم الخدمة طلبك. يمكنك الآن المتابعة للدفع.",
    orderDeclinedTitle: "تم رفض الطلب",
    orderDeclinedMessage: "لقد رفض مقدم الخدمة طلبك.",
    orderAcceptedDescription: "تم قبول هذا الطلب من قبل مقدم الخدمة. يمكنك الآن إجراء الدفع وبدء الخدمة.",
    orderDeclinedDescription: "تم رفض هذا الطلب من قبل مقدم الخدمة.",
    statusPendingApprovalTitle: "بانتظار الموافقة",
    statusPendingApprovalDescriptionSeeker: "تم إرسال طلبك إلى مقدم الخدمة وهو بانتظار موافقته.",
    statusPendingApprovalDescriptionProvider: "هذا الطلب بانتظار موافقتك. يمكنك قبول أو رفض الطلب.",
    statusDeclinedTitle: "مرفوض",
    statusDeclinedDescription: "تم رفض هذا الطلب من قبل مقدم الخدمة.",
    currency: "العملة",
    USD: "دولار أمريكي",
    SAR: "ريال سعودي",
    EGP: "جنيه مصري",
    AED: "درهم إماراتي",
    QAR: "ريال قطري",
    howToUse: "كيفية الاستخدام",
    advertiseWithUs: "أعلن معنا",
    faqTitle: "الأسئلة الشائعة",
    faqDescription: "ابحث عن إجابات للأسئلة الأكثر شيوعاً حول منصتنا.",
    faqQ1: "كيف يمكنني العثور على مقدم خدمة؟",
    faqA1: "يمكنك استخدام شريط البحث في الصفحة الرئيسية للعثور على مقدمي الخدمات بالاسم، الفئة، أو منطقة الخدمة. يمكنك أيضاً تصفح فئات الخدمات.",
    faqQ2: "كيف أصبح مقدم خدمة؟",
    faqA2: "ما عليك سوى النقر على زر 'التسجيل' واختيار 'مقدم خدمة'. املأ تفاصيل ملفك الشخصي، وستكون جاهزاً للانطلاق!",
    faqQ3: "هل استخدام المنصة مجاني؟",
    faqA3: "نعم، البحث والتواصل مع مقدمي الخدمات مجاني. نحن نفرض فقط عمولة صغيرة على الخدمات المكتملة.",
    faqQ4: "ماذا أفعل إذا واجهت مشكلة؟",
    faqA4: "يمكنك التواصل مع فريق الدعم لدينا من خلال صفحة 'اتصل بنا'. نحن هنا للمساعدة!",
    advertiseTitle: "أعلن معنا",
    advertiseDescription: "وصل إلى آلاف العملاء المحتملين عن طريق الإعلان عن خدماتك على منصتنا.",
    adInquiryPlaceholder: "أنا مهتم بالإعلان عن خدماتي...",
    advertisement: "إعلان",
    adPlaceholderTitle: "إعلانك هنا",
    adPlaceholderDescription: "تواصل معنا للإعلان عن خدمتك والوصول إلى المزيد من العملاء!",
    proposedStartDate: "تاريخ البدء المقترح",
    selectStartDate: "اختر تاريخ البدء",
    gracePeriodTitle: "فترة سماح",
    grantGracePeriod: "منح فترة سماح",
    gracePeriodDescription: "امنح مقدم الخدمة فترة سماح لبدء الخدمة. هذا سيمدد الموعد النهائي له لبدء العمل.",
    selectGracePeriod: "اختر فترة السماح",
    oneDay: "يوم واحد",
    twoDays: "يومان",
    threeDays: "ثلاثة أيام",
    gracePeriodGranted: "تم منح فترة سماح لمدة {days} يوم/أيام.",
    startService: "بدء الخدمة",
    serviceStarted: "الخدمة بدأت",
    serviceStartedOn: "الخدمة بدأت في: {date}",
    requestRefund: "طلب استرداد",
    refundReasonLate: "لم يبدأ مقدم الخدمة العمل في الوقت المحدد.",
    refundRequested: "تم طلب استرداد",
    refundRequestedDescription: "تم تقديم طلب استرداد. سيقوم فريق المشرفين بمراجعته.",
    orderPastDue: "الطلب متأخر",
    orderPastDueDescription: "لم يبدأ مقدم الخدمة في الوقت المحدد. يمكنك طلب استرداد أو منح فترة سماح.",
    serviceStartedTitle: "بدأت الخدمة",
    serviceStartedMessage: "لقد بدأ مقدم الخدمة العمل. يمكنك الآن مراقبة التقدم وتحديد أن العمل قد انتهى عند الانتهاء.",
    workFinishedTitle: "العمل انتهى",
    workFinishedMessage: "لقد قام مقدم الخدمة بتحديد أن العمل قد انتهى. يمكنك الآن مراجعة العمل وتحديد أن الطلب قد اكتمل لتحرير الأموال.",
    statusPendingCompletion: "بانتظار الاكتمال",
    statusPendingCompletionTitle: "بانتظار الاكتمال",
    statusPendingCompletionDescriptionSeeker: "لقد قام مقدم الخدمة بتحديد أن العمل قد انتهى. يرجى مراجعة العمل وتحديد أن الطلب قد اكتمل لتحرير الأموال.",
    statusPendingCompletionDescriptionProvider: "لقد قمت بتحديد أن العمل قد انتهى. سيقوم طالب الخدمة الآن بمراجعة العمل وتحديد أن الطلب قد اكتمل.",
    markAsFinished: "تحديد أنه انتهى",
    confirmCompletion: "تأكيد الاكتمال",
    reportProblem: "الإبلاغ عن مشكلة",
    notifications: "الإشعارات",
    noNotifications: "لا توجد إشعارات.",
    markAllAsRead: "وضع الكل كمقروء",
    viewOrder: "عرض الطلب",
    newOrderRequestTitle: "طلب جديد",
    newOrderRequestMessage: "لقد طلب {seekerName} خدمتك.",
    paymentReceivedTitle: "تم استلام الدفع",
    paymentReceivedMessage: "لقد دفع {seekerName} قيمة الطلب. يمكنك الآن بدء الخدمة.",
    allNotifications: "جميع الإشعارات",
    allNotificationsDescription: "عرض جميع إشعاراتك السابقة.",
    noNotificationsYet: "ليس لديك إشعارات بعد.",
    viewAll: "عرض الكل",
    deleteProof: "حذف الإثبات",
    uploadNewProof: "رفع إثبات جديد",
    confirmDeleteProofTitle: "حذف إثبات الدفع؟",
    confirmDeleteProofDescription: "هل أنت متأكد من أنك تريد حذف إثبات الدفع هذا؟ سيتعين عليك رفع إثبات جديد.",
    proofDeletedSuccessTitle: "تم حذف الإثبات",
    proofDeletedSuccessDescription: "تم حذف إثبات الدفع. يمكنك الآن رفع إثبات جديد.",
    deleteFailedTitle: "فشل الحذف",
    proofUploaded: "تم رفع إثبات الدفع.",
    viewProof: "عرض الإثبات",
    paymentProof: "إثبات الدفع",
    continue: "متابعة",
    contactSupport: "الاتصال بالدعم الفني",
    requestSubmittedTitle: "تم إرسال الطلب",
    requestSubmittedDescription: "تم إرسال طلب إعلانك وهو بانتظار مراجعة المشرف.",
    adRequestApprovedTitle: "تمت الموافقة على طلب الإعلان",
    adRequestApprovedMessage: "تمت الموافقة على طلب إعلانك! يمكنك الآن المتابعة للدفع.",
    adRequestRejectedTitle: "تم رفض طلب الإعلان",
    adRequestRejectedMessage: "تم رفض طلب إعلانك. يرجى مراجعة السبب والمحاولة مرة أخرى.",
    adRequests: "طلبات الإعلانات",
    adRequestsDescription: "مراجعة وإدارة جميع طلبات الإعلانات.",
    pending: "معلق",
    approved: "موافق عليه",
    rejected: "مرفوض",
    loginToContactSupport: "يجب عليك تسجيل الدخول للاتصال بالدعم.",
    supportRequestSentTitle: "تم إرسال طلب الدعم",
    supportRequestSentDescription: "تم إرسال طلب الدعم الخاص بك. سنقوم بالرد عليك في أقرب وقت ممكن.",
    supportRequestSentSuccess: "تم إرسال طلب الدعم بنجاح!",
    requestType: "نوع الطلب",
    selectRequestType: "اختر نوع الطلب",
    inquiry: "استفسار",
    complaint: "شكوى",
    paymentIssue: "مشكلة في الدفع",
    messageTooShort: "الرسالة قصيرة جداً.",
    supportRequests: "طلبات الدعم",
    reviewSupportTickets: "مراجعة وإدارة تذاكر الدعم.",
    noSupportRequests: "لا توجد طلبات دعم بعد.",
    noSupportRequestsDescription: "لا توجد تذاكر دعم للمراجعة في الوقت الحالي.",
    statusOpen: "مفتوح",
    statusInProgress: "قيد التقدم",
    statusClosed: "مغلق",
    markAsInProgress: "تحديد كـ قيد التقدم",
    markAsClosed: "تحديد كـ مغلق",
    ticketStatusUpdated: "تم تحديث حالة التذكرة.",
    supportRequestClosedTitle: "تم إغلاق طلب الدعم",
    supportRequestClosedMessage: "تم إغلاق طلب الدعم الخاص بك من قبل فريق المشرفين.",
    supportRequestClosedWithReplyMessage: "تم إغلاق طلب الدعم الخاص بك من قبل فريق المشرفين. تم إرسال رد.",
    supportRequestInProgressTitle: "طلب الدعم قيد التقدم",
    supportRequestInProgressMessage: "طلب الدعم الخاص بك قيد التقدم الآن. فريقنا يراجع حالتك.",
    myAds: "إعلاناتي",
    myAdsDescription: "إدارة طلبات إعلاناتك وإعلاناتك النشطة.",
    newAdRequest: "طلب إعلان جديد",
    noAdRequestsYet: "لا توجد طلبات إعلانات بعد.",
    noAdRequestsYetDescription: "لم ترسل أي طلبات إعلانات بعد.",
    adTitle: "عنوان الإعلان",
    adImage: "صورة الإعلان",
    uploadImage: "رفع صورة",
    changeImage: "تغيير الصورة",
    statusPendingReview: "بانتظار المراجعة",
    statusPendingPayment: "بانتظار الدفع",
    statusPaymentReview: "مراجعة الدفع",
    statusActive: "نشط",
    statusRejected: "مرفوض",
    statusPendingReviewDescription: "إعلانك بانتظار مراجعة فريق المشرفين.",
    statusPendingPaymentDescription: "تمت الموافقة على إعلانك. يرجى إتمام الدفع لتفعيله.",
    statusPaymentReviewDescription: "لقد قمت برفع إثبات الدفع. المشرف يراجعه الآن.",
    statusActiveDescription: "إعلانك الآن نشط ومباشر على المنصة.",
    statusRejectedDescription: "تم رفض إعلانك من قبل المشرف.",
    uploadPaymentProof: "رفع إثبات الدفع",
    adPaymentConfirmedTitle: "تم تأكيد الدفع",
    adPaymentConfirmedMessage: "تم تأكيد دفعك للإعلان. الإعلان الآن نشط!",
    adPaymentRejectedTitle: "تم رفض الدفع",
    adPaymentRejectedMessage: "تم رفض إثبات الدفع الخاص بك. يرجى رفع صورة واضحة للدفع.",
    adRequestInPaymentReviewMessage: "إثبات الدفع الخاص بك قيد المراجعة من قبل فريق المشرفين.",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    termsTitle: "شروط الخدمة",
    termsDescription: "شروطنا وأحكامنا لاستخدام المنصة.",
    termsContent: "هذا هو محتوى بديل لشروط الخدمة...",
    privacyTitle: "سياسة الخصوصية",
    privacyDescription: "سياسة الخصوصية الخاصة بنا حول كيفية تعاملنا مع بياناتك.",
    privacyContent: "هذا هو محتوى بديل لسياسة الخصوصية...",
    identityVerification: "تفعيل الهوية",
    identityVerificationDescription: "قم بتفعيل هويتك لبناء الثقة مع المستخدمين وفتح المزيد من الميزات.",
    verificationNotSubmitted: "لم يتم الإرسال",
    uploadDocuments: "رفع المستندات",
    reUploadDocuments: "إعادة رفع المستندات",
    verificationPendingTitle: "تفعيل معلق",
    verificationPendingDescription: "تم إرسال مستنداتك وهي بانتظار مراجعة المشرف.",
    verificationVerifiedTitle: "تم تفعيل الهوية",
    verificationVerifiedDescription: "تم تفعيل هويتك بنجاح!",
    verificationRejectedTitle: "تم رفض التفعيل",
    verificationRejectedDescription: "تم رفض تفعيل هويتك. يرجى مراجعة السبب وإعادة رفع مستنداتك.",
    verificationDocsUploadedTitle: "تم رفع المستندات",
    verificationDocsUploadedDescription: "تم رفع مستندات التفعيل الخاصة بك وهي بانتظار المراجعة.",
    providerVerifications: "تفعيل مقدمي الخدمات",
    noPendingVerifications: "لا توجد طلبات تفعيل معلقة.",
    noPendingVerificationsDescription: "لا توجد طلبات تفعيل مقدمي خدمات للمراجعة في الوقت الحالي.",
    approve: "موافقة",
    uploadedDocuments: "المستندات المرفوعة",
    confirmRejectVerificationTitle: "هل أنت متأكد من أنك تريد رفض هذا التفعيل؟",
    confirmRejectVerificationDescription: "هذا سيعلم مقدم الخدمة بأن تفعيله قد تم رفضه.",
    verifiedProvider: "مقدم خدمة موثق",
    noDisputes: "لا توجد نزاعات.",
    noDisputesDescription: "لا توجد نزاعات للمراجعة في الوقت الحالي.",
    viewDispute: "عرض النزاع",
    disputeDetails: "تفاصيل النزاع",
    disputeTimeline: "الجدول الزمني للنزاع",
    disputeReason: "سبب النزاع",
    disputeConversation: "محادثة النزاع",
    resolution: "القرار",
    adminNotes: "ملاحظات المشرف",
    sideWithSeeker: "التحيز لطالب الخدمة",
    sideWithProvider: "التحيز لمقدم الخدمة",
    submitResolution: "إرسال القرار",
    confirmResolutionTitle: "تأكيد القرار",
    confirmResolutionDescription: "هل أنت متأكد من أنك تريد إرسال هذا القرار؟ هذا الإجراء لا يمكن التراجع عنه.",
    resolutionSubmitted: "تم إرسال القرار",
    failedToSubmitResolution: "فشل إرسال القرار. يرجى المحاولة مرة أخرى.",
    disputeResolvedTitle: "تم حل النزاع",
    disputeResolvedSeekerFavorMessage: "تم حل النزاع لصالح طالب الخدمة. سيتم تحرير الأموال له.",
    disputeResolvedProviderFavorMessage: "تم حل النزاع لصالح مقدم الخدمة. سيتم تحرير الأموال له.",
    orderId: "معرف الطلب",
    orderSummary: "ملخص الطلب",
    amount: "المبلغ",
    disputedOn: "تم النزاع عليه في",
    sendMessageToParties: "أرسل رسالة إلى الطرفين المشاركين في النزاع.",
    explainDecision: "اشرح قرارك وأسبابك للطرفين.",
    orderCouldNotBeLoaded: "تعذر تحميل تفاصيل الطلب.",
    couldNotLoadMessages: "تعذر تحميل الرسائل.",
    resolutionNotesRequired: "ملاحظات القرار مطلوبة.",
    failedToFetchDisputeDetails: "فشل في جلب تفاصيل النزاع.",
    orderIdMissing: "معرف الطلب مفقود.",
    admin: "مشرف",
    unknownUser: "مستخدم غير معروف",
    partiesInvolved: "الأطراف المعنية",
    messageSeeker: "مراسلة طالب الخدمة",
    analyzingBioTitle: "جاري تحليل السيرة الذاتية",
    analyzingBioDescription: "نقوم بتحليل سيرتك الذاتية لاقتراح فئة.",
    categoryAutoDetectedTitle: "تم اكتشاف الفئة تلقائيًا",
    categoryAutoDetectedDescription: "لقد قمنا بتعيين فئتك الأساسية إلى: {category}. يمكنك تغييرها يدويًا إذا لزم الأمر.",
    aiCategorizationUnavailableTitle: "تصنيف الذكاء الاصطناعي غير متوفر",
    aiCategorizationUnavailableDescription: "خدمة تصنيف الذكاء الاصطناعي غير متوفرة حاليًا.",
    adBodyTooLong: "محتوى الإعلان طويل جداً.",
    adTitleTooLong: "عنوان الإعلان طويل جداً.",
    adTitleTooShort: "عنوان الإعلان قصير جداً."
  }
};



New problems detected after saving the file:
src/lib/translations.ts
- [ts Error] Line 145: Duplicate identifier 'disputeResolution'.
- [ts Error] Line 307: Duplicate identifier 'messageProvider'.
- [ts Error] Line 623: Duplicate identifier 'disputeResolution'.
- [ts Error] Line 658: Duplicate identifier 'messageProvider'.
- [ts Error] Line 703: Type '{ appName: string; toggleNavigationMenu: string; dashboardMenu: string; dashboardMenuDesc: string; tagline: string; home: string; services: string; login: string; register: string; logout: string; ... 627 more ...; messageSeeker: string; }' is missing the following properties from type 'Translations': analyzingBioTitle, analyzingBioDescription, categoryAutoDetectedTitle, categoryAutoDetectedDescription, and 2 more.
- [ts Error] Line 1342: An object literal cannot have multiple properties with the same name.
- [ts Error] Line 1344: Type '{ appName: string; toggleNavigationMenu: string; dashboardMenu: string; dashboardMenuDesc: string; tagline: string; home: string; services: string; login: string; register: string; logout: string; ... 627 more ...; messageSeeker: string; }' is missing the following properties from type 'Translations': analyzingBioTitle, analyzingBioDescription, categoryAutoDetectedTitle, categoryAutoDetectedDescription, and 2 more.
- [ts Error] Line 1983: An object literal cannot have multiple properties with the same name.
src/lib/ar.ts
- [ts Error] Line 3: Type '{ appName: string; toggleNavigationMenu: string; dashboardMenu: string; dashboardMenuDesc: string; tagline: string; home: string; services: string; login: string; register: string; logout: string; ... 627 more ...; messageSeeker: string; }' is missing the following properties from type 'Translations': analyzingBioTitle, analyzingBioDescription, categoryAutoDetectedTitle, categoryAutoDetectedDescription, and 2 more.<environment_details>
# VSCode Visible Files
src/lib/ar.ts
src/lib/translations.ts

# VSCode Open Tabs
prisma/schema.prisma
.env
src/components/layout/Header.tsx
src/lib/translations.ts
src/app/layout.tsx
src/app/(auth)/register/RegisterClient.tsx
src/app/(auth)/login/page.tsx
src/app/(auth)/forgot-password/page.tsx
.gitignore
src/app/api/auth/[...nextauth]/route.ts
src/lib/prisma.ts
next.config.ts

# Recently Modified Files
These files have been modified since you last accessed them (file was just edited so you may need to re-read it before editing):
src/lib/translations.ts

# Current Time
8/7/2025, 8:57:23 AM (UTC, UTC+0:00)

# Context Window Usage
64,163 / 1,048.576K tokens used (6%)

# Current Mode
ACT MODE
</environment_details>
<environment_details>
# VSCode Visible Files
src/lib/ar.ts

# VSCode Open Tabs
prisma/schema.prisma
.env
src/components/layout/Header.tsx
src/lib/translations.ts
src/lib/ar.ts
src/lib/en.ts
src/app/layout.tsx
src/app/(auth)/register/RegisterClient.tsx
src/app/(auth)/login/page.tsx
src/app/(auth)/forgot-password/page.tsx
.gitignore
src/app/api/auth/[...nextauth]/route.ts
src/lib/prisma.ts
next.config.ts

# Current Time
8/7/2025, 9:21:46 AM (UTC, UTC+0:00)

# Context Window Usage
140,250 / 1,048.576K tokens used (13%)

# Current Mode
ACT MODE
</environment_details>
