import { Translations } from './translations';

export const en: Translations = {
    appName: "Khidmap",
    toggleNavigationMenu: "Toggle navigation menu",
    dashboardMenu: "Dashboard Menu",
    dashboardMenuDesc: "Navigation links for the dashboard.",
    tagline: "Find the best local service providers",
    home: "Home",
    services: "Services",
    login: "Login",
    register: "Register",
    logout: "Logout",
    profile: "Profile",
    dashboard: "Dashboard",
    language: "Language",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    searchPlaceholder: "Search providers by name, category...",
    search: "Search",
    serviceProviders: "Service Providers",
    serviceSeekers: "Service Seekers",
    registerAs: "Register as",
    provider: "Service Provider",
    seeker: "Service Seeker",
    email: "Email",
    password: "Password",
    name: "Full Name",
    realNameHelpText: "Please use your real name as it appears on bank documents.",
    bankNamePlaceholder: "e.g. John Doe",
    qualifications: "About Me / Bio",
    phoneNumber: "Phone Number",
    address: "Address / Service Location",
    serviceAreas: "Service Areas",
    serviceAreasPlaceholder: "e.g., Downtown, North Suburbs (comma-separated)",
    category: "Category",
    plumbing: "Plumbing",
    electrical: "Electrical",
    carpentry: "Carpentry",
    painting: "Painting",
    homeCleaning: "Home Cleaning",
    construction: "Construction",
    plastering: "Plastering",
    other: "Other Services",
    searchHistory: "Search History",
    noResultsFound: "No results found.",
    loading: "Loading...",
    submit: "Submit",
    viewDetails: "View Details",
    errorOccurred: "An error occurred.",
    welcomeTo: "Welcome to",
    findSkilledArtisans: "Find skilled artisans for your needs.",
    orPostYourServices: "Or post your services and reach new customers.",
    getStarted: "Get Started",
    browseServices: "Browse Services",
    joinAsProvider: "Join as a Provider",
    joinAsSeeker: "Join as a Seeker",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    createAccount: "Create Account",
    fillYourProfile: "Fill your profile details",
    serviceDetails: "Service Details",
    contactInfo: "Contact Information",
    saveChanges: "Save Changes",
    profileUpdatedSuccessfully: "Profile updated successfully!",
    selectCategory: "Select Category",
    serviceCategory: "Service Category",
    searchByAddressOrKeyword: "Search by Address or Keyword",
    recentSearches: "Recent Searches",
    clearHistory: "Clear History",
    noHistoryYet: "You have no search history yet.",
    requiredField: "This field is required",
    invalidEmail: "Invalid email address",
    passwordTooShort: "Password must be at least 6 characters",
    passwordsDoNotMatch: "Passwords do not match",
    confirmPassword: "Confirm Password",
    emailVerificationSent: "Email Verification Sent",
    checkYourEmailForVerification: "A verification link has been sent to your email. Please check your inbox (and spam folder) to activate your account.",
    contactUs: "Contact Us",
    adminDashboard: "Admin Dashboard",
    welcomeAdmin: "Welcome, Admin!",
    adminPlaceholder: "This is the admin dashboard. More features coming soon.",
    selectService: "Select Service",
    hidePassword: "Hide password",
    showPassword: "Show password",
    authServiceUnavailable: "Authentication service is currently unavailable. Please try again later or contact support.",
    serviceUnavailableTitle: "Service Unavailable",
    serviceUnavailableMessage: "A core service (like authentication or database) is currently not configured or unavailable. Please try again later or contact support.",
    coreServicesUnavailableDashboard: "Core services are unavailable. The dashboard cannot be loaded at this time. Please try again later or contact support.",
    loginSuccessful: "Login Successful",
    welcomeBackUser: "Welcome back, {userName}!",
    loginFailedGeneric: "Login Failed. Please check your credentials.",
    invalidCredentials: "Invalid email or password. Please try again.",
    networkError: "Network error. Please check your internet connection.",
    loginFailedTitle: "Login Failed",
    registrationFailedGeneric: "Registration Failed. Please try again.",
    emailAlreadyInUse: "This email is already registered. Please login or use a different email.",
    passwordTooWeak: "Password is too weak. Please choose a stronger password.",
    registrationFailedTitle: "Registration Failed",
    userNotAuthenticated: "User not authenticated. Please log in again.",
    userNotIdentified: "User not identified. Please log in again.",
    coreServicesUnavailable: "Core services are not ready or unavailable.",
    providerInfoMissing: "Provider information is missing. Please try again.",
    invalidDate: "Invalid Date",
    delete: "Delete",
    cancel: "Cancel",
    welcome: "Welcome!",
    completeYourProfile: "Please complete your provider profile.",
    couldNotFetchProfile: "Could not fetch profile data.",
    authError: "Authentication Error",
    userNotAuthOrServiceUnavailable: "User not authenticated or service unavailable.",
    profileChangesSaved: "Your profile changes have been saved.",
    failedUpdateProfile: "Failed to update profile.",
    profilePageDescription: "Manage your provider profile details for {appName}.",
    profileEditingUnavailable: "Profile editing is currently unavailable because core services are not configured.",
    profileHelpTextCategory: "Select your primary service category.",
    searchHistoryClearedTitle: "Search History Cleared",
    searchHistoryClearedSuccess: "Your search history has been successfully cleared.",
    searchHistoryPageDescription: "Review your past service searches.",
    confirmClearHistoryTitle: "Are you sure you want to clear your search history?",
    confirmClearHistoryDescription: "This action cannot be undone. This will permanently delete all your search history entries.",
    noHistoryYetDescription: "Your search history is empty. Start searching for services to see them here.",
    searchedOn: "Searched on:",
    repeatSearch: "Repeat Search",
    failedLoadServices: "Failed to load services.",
    backButton: "Back",
    backToSearch: "Back to Search",
    postedOnFull: "Joined on:",
    serviceCategoriesTitle: "Service Categories:",
    servesAreasTitle: "Service Areas",
    contactProvider: "Contact {providerName}",
    providerDetailsNotAvailable: "Provider details are not available.",
    searchServicesPageDescription: "Find skilled artisans by searching by name, service type, or keywords.",
    tryDifferentKeywords: "Try searching with different keywords or check your spelling.",
    noServicesAvailableYet: "No Service Providers Available Yet",
    checkBackLater: "There are currently no service providers registered. Check back later!",
    switchToDarkMode: "Switch to Dark Mode",
    switchToLightMode: "Switch to Light Mode",
    unauthorized: "Unauthorized",
    loginAsAdmin: "Please log in as admin.",
    accessDenied: "Access Denied",
    notAuthorizedViewPage: "You are not authorized to view this page.",
    adminDashboardDescription: "Manage users, services, and application settings.",
    paymentApprovalsDescription: "Review and approve pending payments.",
    reviewProviderVerifications: "Review provider verification requests.",
    disputeResolutionDescription: "Review and resolve user disputes.",
    adminDashboardUnavailable: "Admin Dashboard is currently unavailable because core services are not configured.",
    logoutFailed: "Logout Failed",
    goToHomepage: "Go to Homepage",
    redirectingToLogin: "Redirecting to login...",
    verifyingUserRole: "Verifying user role...",
    verifyEmailPromptTitle: "Please verify your email address.",
    verifyEmailPromptMessage: "A verification link was sent to {email}. Check your inbox (and spam folder).",
    resendVerificationEmail: "Resend verification email",
    verificationEmailResent: "Verification Email Resent",
    checkYourEmail: "Please check your email.",
    errorResendingVerificationEmail: "Could not resend verification email.",
    welcomeToDashboardUser: "Welcome to your Dashboard, {userName}!",
    welcomeToDashboardProvider: "Welcome to your Provider Dashboard!",
    welcomeToDashboardSeeker: "Welcome to your Seeker Dashboard!",
    profileDescriptionProvider: "Update your personal and service information.",
    searchDescriptionSeeker: "Find skilled artisans for your needs.",
    searchHistoryDescriptionSeeker: "Review your past service searches.",
    dashboardTaglineProvider: "Manage your profile and connect with customers.",
    dashboardTaglineSeeker: "Find and rate the best services for your needs.",
    dashboardBannerAlt: "Dashboard banner with tools or workspace imagery",
    contactPageTitle: "Contact Us",
    contactPageDescription: "Have questions or feedback? Reach out to us!",
    yourName: "Your Name",
    yourEmail: "Your Email",
    subject: "Subject",
    message: "Message",
    sendMessage: "Send Message",
    messageSentSuccessTitle: "Message Sent!",
    messageSentSuccessDescription: "Thank you for your message. We'll get back to you soon.",
    messageSentErrorTitle: "Error Sending Message",
    messageSentErrorDescription: "Sorry, there was an issue sending your message. Please try again later.",
    contactFormIntro: "We'd love to hear from you! Please fill out the form below and we'll get in touch as soon as possible.",
    formSubmitActivationNote: "Note: For this form to work, the owner of mobusinessarena@gmail.com needs to activate it once via an email from FormSubmit.co after the first submission attempt.",
    tryAgain: "Try Again",
    backToDashboard: "Back to Dashboard",
    plumbingDescription: "Expert plumbing services for repairs, installations, and maintenance.",
    electricalDescription: "Safe and reliable electrical solutions for your home and business.",
    carpentryDescription: "Skilled carpentry for furniture, repairs, and custom projects.",
    paintingDescription: "Professional painting services for a fresh new look.",
    homeCleaningDescription: "Reliable home cleaning services for a spotless living space.",
    constructionDescription: "Comprehensive construction services from foundation to finish.",
    plasteringDescription: "Quality plastering for smooth and durable walls and ceilings.",
    otherServicesDescription: "Various other services to meet your unique needs.",
    reviews: "Reviews",
    averageRating: "Average Rating",
    noReviewsYet: "No reviews yet",
    rateThisProvider: "Rate this Provider",
    rating: "Your Rating",
    comment: "Your Comment (optional)",
    submitRating: "Submit Rating",
    loginToRate: "You must be logged in to submit a rating.",
    selectRating: "Please select a star rating before submitting.",
    ratingSubmitted: "Rating Submitted",
    thankYouForFeedback: "Thank you for your feedback!",
    failedSubmitRating: "Failed to submit rating.",
    providerNotFound: "Provider not found.",
    providerIdMissing: "Provider ID is missing.",
    failedLoadProviderDetails: "Failed to load provider details.",
    firestoreIndexError: "Firestore index is missing. Check your database configuration.",
    permissionDeniedError: "You do not have permission to perform this action.",
    of: "of", // e.g. 4.5 of 5 stars
    viewProfile: "View Profile",
    location: "Location",
    useCurrentLocation: "Use Current Location",
    locationSet: "Location set successfully!",
    locationError: "Failed to get location. Please enable location services.",
    findNearMe: "Find Near Me",
    findingLocation: "Finding your location...",
    sortedByDistance: "Sorted by Distance",
    kmAway: "km away",
    locationPermissionDenied: "Location permission denied. Please enable it in your browser settings to use this feature.",
    locationNotSet: "Location not set. Please set your location to use this feature.",
    locationUnavailable: "Location services are unavailable.",
    locationHelpText: "Enter a city, neighborhood, or specific address.",
    forgotPassword: "Forgot Password?",
    forgotPasswordDescription: "Enter your email to receive a password reset link.",
    sendResetLink: "Send Reset Link",
    resetLinkSentTitle: "Reset Link Sent",
    resetLinkSentDescription: "Check your email for a password reset link.",
    resetPasswordErrorTitle: "Error Sending Reset Link",
    userNotFound: "User not found with this email address.",
    backToLogin: "Back to Login",
    settings: "Settings",
    manageAccountSettings: "Manage your account settings.",
    dangerZone: "Danger Zone",
    dangerZoneDescription: "Actions in this section are irreversible.",
    deleteAccount: "Delete Account",
    deleteAccountDescription: "Permanently delete your account and all associated data.",
    confirmDeleteAccountTitle: "Confirm Account Deletion",
    confirmDeleteAccountDescription: "Are you absolutely sure you want to delete your account? This action cannot be undone.",
    confirmDelete: "Confirm Delete",
    accountDeletedTitle: "Account Deleted",
    accountDeletedSuccess: "Your account has been successfully deleted. We're sorry to see you go!",
    accountDeletionFailed: "Account Deletion Failed",
    accountDeletionError: "Failed to delete your account. Please try again or contact support.",
    requiresRecentLoginError: "You must be logged in recently to perform this action. Please log out and log in again.",
    callNow: "Call Now",
    contactOnWhatsApp: "Contact on WhatsApp",
    aboutProvider: "About {name}",
    specialties: "Specialties",
    portfolioTitle: "Portfolio",
    portfolioDescription: "Showcase your work with images and videos.",
    mediaUploadDescription: "You can upload up to 5 images or videos (max 10MB each).",
    uploadMedia: "Upload Media",
    uploading: "Uploading...",
    portfolioLimitReachedTitle: "Portfolio Limit Reached",
    portfolioLimitReachedDescription: "You have reached the maximum limit of 5 portfolio items.",
    fileTooLargeTitle: "File Too Large",
    fileTooLargeDescription: "The file size exceeds the 10MB limit. Please upload a smaller file.",
    unsupportedFileTypeTitle: "Unsupported File Type",
    unsupportedFileTypeDescription: "We only support JPG, PNG, and MP4 formats.",
    fileUploadedSuccessTitle: "File Uploaded",
    fileUploadErrorTitle: "Upload Failed",
    fileUploadErrorDescription: "An error occurred during the upload. Please try again.",
    storageUnauthorizedError: "Unauthorized to upload files.",
    storageUnauthorizedDeleteError: "Unauthorized to delete this file.",
    fileDeletedSuccessTitle: "File Deleted",
    fileDeleteErrorTitle: "Delete Failed",
    fileDeleteErrorDescription: "An error occurred while deleting the file. Please try again.",
    confirmDeleteFileTitle: "Delete File?",
    confirmDeleteFileDescription: "Are you sure you want to delete this file? This action cannot be undone.",
    noPortfolioItems: "No portfolio items uploaded yet.",
    fileNotFoundInStorage: "File not found in storage.",
    imageRejectedTitle: "Image Rejected",
    imageRejectedDescription: "The uploaded image was rejected due to inappropriate content. Please upload a suitable image.",
    videoRejectedTitle: "Video Rejected",
    videoRejectedDescription: "The uploaded video was rejected due to inappropriate content. Please upload a suitable video.",
    analyzingImageTitle: "Analyzing Image",
    analyzingImageDescription: "We are analyzing your image for safety and compliance.",
    analyzingVideoTitle: "Analyzing Video",
    analyzingVideoDescription: "We are analyzing your video for safety and compliance. This may take a moment.",
    images: "Images",
    videos: "Videos",
    portfolioImage: "Portfolio Image",
    portfolioVideo: "Portfolio Video",
    fullscreenViewOf: "Fullscreen view of {title}",
    whatsappMessage: "Hello {providerName}, I saw your profile on {appName} and would like to inquire about your services.",
    aiAdGenerationTitle: "AI Ad Generation",
    aiAdGenerationDescription: "Let our AI create a compelling ad for you based on your profile.",
    primaryService: "Primary Service",
    primaryServicePlaceholder: "e.g., Electrician, Plumber",
    serviceAreasPlaceholderAI: "e.g., Downtown, North Suburbs",
    commaSeparated: "Comma-separated",
    contactInfoOptional: "Contact Info (Optional)",
    contactInfoPlaceholder: "e.g., Your phone number or email",
    keywordsOptional: "Keywords (Optional)",
    keywordsPlaceholder: "e.g., Quick, Affordable, Professional",
    generateAd: "Generate Ad",
    reviewAiAd: "Review your AI-Generated Ad",
    reviewAiAdDescription: "Review the ad created by our AI. You can edit it before submitting.",
    adBody: "Ad Body",
    adImageRequired: "Ad Image Required",
    backToEditInfo: "Back to Edit Info",
    submitForApproval: "Submit for Approval",
    aiGenerationFailed: "Failed to generate ad. Please try again.",
    validationError: "Validation Error",
    provideServiceType: "Please provide a primary service type.",
    provideServiceArea: "Please provide at least one service area.",
    profileNameMissing: "Your profile name is missing. Please update your profile.",
    imageRequiredForAd: "An image is required to create an ad.",
    adImageHint: "Upload an image that represents your service.",
    createNewAd: "Create a New Ad",
    chooseAdCreationMethod: "Choose how you want to create your ad:",
    createWithAi: "Create with AI",
    createWithAiDescription: "Let our AI generate a professional ad for you based on your profile details.",
    createManually: "Create Manually",
    createManuallyDescription: "Write your own ad from scratch.",
    startNow: "Start Now",
    createAdManually: "Create Ad Manually",
    loginToSubmitAd: "You must be logged in to submit an ad.",
    adTitleTooShort: "Ad title is too short.",
    adTitleTooLong: "Ad title is too long.",
    adBodyTooShort: "Ad body is too short.",
    messages: "Messages",
    messageProvider: "Message {providerName}",
    startChatError: "Failed to start chat. Please try again.",
    startConversation: "Start a Conversation",
    messageSent: "Message sent!",
    conversations: "Conversations",
    noConversations: "No conversations yet.",
    noConversationsDescription: "Start a conversation with a service provider or seeker.",
    selectConversation: "Select a Conversation",
    selectConversationDescription: "Choose a conversation from the left to view messages.",
    typeYourMessage: "Type your message...",
    loginToMessage: "You must be logged in to send a message.",
    you: "You",
    image: "Image",
    video: "Video",
    audioRecordingNotSupported: "Audio Recording Not Supported",
    audioRecordingNotSupportedDescription: "Your browser does not support audio recording.",
    microphoneAccessDenied: "Microphone Access Denied",
    microphoneAccessDeniedDescription: "Please enable microphone access in your browser settings to record audio.",
    changePassword: "Change Password",
    changePasswordDescription: "Send a password reset email to change your password.",
    sendResetEmail: "Send Reset Email",
    resetEmailSent: "Reset Email Sent",
    resetEmailSentDescription: "A password reset email has been sent to your email address. Please check your inbox (and spam folder) to change your password.",
    roleMissingTitle: "Role Missing",
    roleMissingDescription: "User role is not set. Please log in again.",
    profileNotFoundTitle: "Profile Not Found",
    profileNotFoundDescription: "User profile was not found.",
    videoCall: "Video Call",
    audioCall: "Audio Call",
    incomingCall: "Incoming Call",
    isCallingYou: "{userName} is calling you...",
    accept: "Accept",
    decline: "Decline",
    callFailed: "Call Failed",
    initiatingCall: "Initiating call...",
    callAccepted: "Call Accepted",
    callEnded: "Call Ended",
    callHasBeenTerminated: "The call has been terminated.",
    connecting: "Connecting...",
    ringing: "Ringing...",
    mediaAccessDeniedTitle: "Media Access Denied",
    mediaAccessDeniedDescription: "Please grant camera and microphone access in your browser settings to make calls.",
    cameraAccessRequired: "Camera access is required for video calls. Please enable it in your browser settings.",
    enableVideoCalls: "Enable Video Calls",
    enableVideoCallsDescription: "Allow other users to make video calls to you.",
    missedCall: "Missed Call",
    callDeclined: "Call Declined",
    callDuration: "Call Duration",
    videoCallLog: "Video Call",
    audioCallLog: "Audio Call",
    serviceAmount: "Service Amount",
    enterServiceAmount: "Enter the total service amount",
    platformCommission: "Platform Commission",
    providerPayout: "Provider Payout",
    myOrders: "My Orders",
    myOrdersDescriptionSeeker: "View the status of your service requests and payments.",
    myOrdersDescriptionProvider: "View the status of service requests and manage your payments.",
    noOrdersYet: "No orders yet.",
    noOrdersYetDescription: "You haven't requested or received any services yet. Start Browse now!",
    pendingPayment: "Pending Payment",
    paid: "Paid",
    completed: "Completed",
    disputed: "Disputed",
    resolved: "Resolved",
    paymentApprovals: "Payment Approvals",
    paymentRejectedTitle: "Payment Proof Rejected",
    paymentRejectedMessage: "The payment proof for your order with {userName} has been rejected. Please upload a new proof.",
    paymentPendingTitle: "Payment Proof Uploaded",
    paymentPendingDescription: "A payment proof has been uploaded by {userName} and is awaiting your approval.",
    paymentApprovedTitle: "Payment Approved",
    paymentApprovedDescription: "You have approved the payment. The provider can now start the service.",
    orderCompletedTitle: "Order Completed",
    orderCompletedMessage: "The order with {userName} has been marked as completed. The funds will be released to the provider shortly.",
    orderDisputedTitle: "Order Disputed",
    orderDisputedMessage: "A dispute has been raised for the order with {userName}.",
    orderDisputedDescription: "A dispute has been raised. Our admin team will review the case and contact both parties.",
    approveManually: "Approve Manually",
    rejectManually: "Reject Manually",
    confirmRejectPaymentTitle: "Are you sure you want to reject this payment?",
    confirmRejectPaymentDescription: "If you reject this payment, the seeker will be notified to upload a new proof.",
    reject: "Reject",
    rejectionReason: "Reason for Rejection (optional)",
    rejectionReasonPlaceholder: "e.g., Unclear image, wrong amount...",
    rejectionFailedTitle: "Rejection Failed",
    rejectionSuccessTitle: "Payment Rejected",
    rejectionSuccessDescription: "The seeker has been notified to upload a new proof.",
    requestService: "Request Service",
    requestingServiceFrom: "Requesting service from {providerName}",
    serviceDescription: "Service Description",
    describeJobDetailPlaceholder: "Describe the job in detail...",
    providerWillSeeDescription: "The provider will see this description to understand your request.",
    submitRequest: "Submit Request",
    descriptionRequired: "Service description is required.",
    invalidAmount: "Invalid amount. Please enter a valid number.",
    enterValidServiceAmount: "Please enter a valid service amount.",
    orderCreatedSuccessTitle: "Service Request Sent",
    orderCreatedSuccessDescription: "Your service request has been sent to the provider. You will be notified once it's accepted.",
    failedToCreateOrder: "Failed to create service request. Please try again.",
    loginToRequestService: "You must be logged in to request a service.",
    backToProfile: "Back to Profile",
    pendingApproval: "Pending Approval",
    orderCreatedAwaitingApprovalDescription: "Your request is awaiting the provider's approval.",
    acceptOrder: "Accept Order",
    declineOrder: "Decline Order",
    orderAccepted: "Order Accepted",
    orderDeclined: "Order Declined",
    orderAcceptedTitle: "Order Accepted!",
    orderAcceptedMessage: "The provider has accepted your service request. You can now proceed to payment.",
    orderDeclinedTitle: "Order Declined",
    orderDeclinedMessage: "The provider has declined your service request.",
    orderAcceptedDescription: "This order has been accepted by the provider. You can now make the payment and start the service.",
    orderDeclinedDescription: "This order has been declined by the provider.",
    statusPendingApprovalTitle: "Pending Approval",
    statusPendingApprovalDescriptionSeeker: "Your request has been sent to the provider and is awaiting their approval.",
    statusPendingApprovalDescriptionProvider: "This order is awaiting your approval. You can accept or decline the request.",
    statusDeclinedTitle: "Declined",
    statusDeclinedDescription: "This order was declined by the provider.",
    currency: "Currency",
    USD: "USD",
    SAR: "SAR",
    EGP: "EGP",
    AED: "AED",
    QAR: "QAR",
    howToUse: "How to Use",
    advertiseWithUs: "Advertise With Us",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Find answers to the most common questions about our platform.",
    faqQ1: "How do I find a service provider?",
    faqA1: "You can use the search bar on the homepage to find providers by name, category, or service area. You can also browse through the service categories.",
    faqQ2: "How do I become a service provider?",
    faqA2: "Simply click on the 'Register' button and choose 'Service Provider'. Fill out your profile details, and you're good to go!",
    faqQ3: "Is it free to use the platform?",
    faqA3: "Yes, searching and connecting with providers is free. We only charge a small commission on completed services.",
    faqQ4: "What should I do if I have a problem?",
    faqA4: "You can contact our support team through the 'Contact Us' page. We're here to help!",
    advertiseTitle: "Advertise with Us",
    advertiseDescription: "Reach thousands of potential customers by advertising your services on our platform.",
    adInquiryPlaceholder: "I'm interested in advertising my services...",
    advertisement: "Advertisement",
    adPlaceholderTitle: "Your Ad Here",
    adPlaceholderDescription: "Contact us to advertise your service and reach more customers!",
    proposedStartDate: "Proposed Start Date",
    selectStartDate: "Select Start Date",
    gracePeriodTitle: "Grace Period",
    grantGracePeriod: "Grant Grace Period",
    gracePeriodDescription: "Grant a grace period to the provider to start the service. This will extend the deadline for them to start the work.",
    selectGracePeriod: "Select Grace Period",
    oneDay: "1 Day",
    twoDays: "2 Days",
    threeDays: "3 Days",
    gracePeriodGranted: "A grace period of {days} day(s) has been granted.",
    startService: "Start Service",
    serviceStarted: "Service Started",
    serviceStartedOn: "Service started on {date}",
    requestRefund: "Request Refund",
    refundReasonLate: "The provider did not start the service on time.",
    refundRequested: "Refund Requested",
    refundRequestedDescription: "A refund request has been submitted. The admin team will review it.",
    orderPastDue: "Order Past Due",
    orderPastDueDescription: "The provider has not started the service on time. You can request a refund or grant a grace period.",
    serviceStartedTitle: "Service Started",
    serviceStartedMessage: "The provider has started the service. You can now monitor the progress and mark it as finished when the work is done.",
    workFinishedTitle: "Work Finished",
    workFinishedMessage: "The provider has marked the work as finished. You can now review the work and mark the order as completed to release the funds.",
    statusPendingCompletion: "Pending Completion",
    statusPendingCompletionTitle: "Pending Completion",
    statusPendingCompletionDescriptionSeeker: "The provider has marked the work as finished. Please review the work and mark the order as completed to release the funds.",
    statusPendingCompletionDescriptionProvider: "You have marked the work as finished. The seeker will now review the work and mark the order as completed.",
    markAsFinished: "Mark as Finished",
    confirmCompletion: "Confirm Completion",
    reportProblem: "Report a Problem",
    notifications: "Notifications",
    noNotifications: "No notifications.",
    markAllAsRead: "Mark All as Read",
    viewOrder: "View Order",
    newOrderRequestTitle: "New Order Request",
    newOrderRequestMessage: "{seekerName} has requested your service.",
    paymentReceivedTitle: "Payment Received",
    paymentReceivedMessage: "{seekerName} has paid for the order. You can now start the service.",
    allNotifications: "All Notifications",
    allNotificationsDescription: "View all your past notifications.",
    noNotificationsYet: "You have no notifications yet.",
    viewAll: "View All",
    deleteProof: "Delete Proof",
    uploadNewProof: "Upload New Proof",
    confirmDeleteProofTitle: "Delete Payment Proof?",
    confirmDeleteProofDescription: "Are you sure you want to delete this payment proof? You will have to upload a new one.",
    proofDeletedSuccessTitle: "Proof Deleted",
    proofDeletedSuccessDescription: "The payment proof has been deleted. You can now upload a new one.",
    deleteFailedTitle: "Delete Failed",
    proofUploaded: "Payment proof uploaded.",
    viewProof: "View Proof",
    paymentProof: "Payment Proof",
    continue: "Continue",
    contactSupport: "Contact Support",
    requestSubmittedTitle: "Request Submitted",
    requestSubmittedDescription: "Your ad request has been submitted and is awaiting admin review.",
    adRequestApprovedTitle: "Ad Request Approved",
    adRequestApprovedMessage: "Your ad request has been approved! You can now proceed to payment.",
    adRequestRejectedTitle: "Ad Request Rejected",
    adRequestRejectedMessage: "Your ad request has been rejected. Please review the reason and try again.",
    adRequests: "Ad Requests",
    adRequestsDescription: "Review and manage all ad requests.",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    loginToContactSupport: "You must be logged in to contact support.",
    supportRequestSentTitle: "Support Request Sent",
    supportRequestSentDescription: "Your support request has been sent. We'll get back to you as soon as possible.",
    supportRequestSentSuccess: "Support request sent successfully!",
    requestType: "Request Type",
    selectRequestType: "Select a request type",
    inquiry: "Inquiry",
    complaint: "Complaint",
    paymentIssue: "Payment Issue",
    messageTooShort: "Message is too short.",
    supportRequests: "Support Requests",
    reviewSupportTickets: "Review and manage support tickets.",
    noSupportRequests: "No support requests yet.",
    noSupportRequestsDescription: "There are no support tickets to review at the moment.",
    statusOpen: "Open",
    statusInProgress: "In Progress",
    statusClosed: "Closed",
    markAsInProgress: "Mark as In Progress",
    markAsClosed: "Mark as Closed",
    ticketStatusUpdated: "Ticket status updated.",
    supportRequestClosedTitle: "Support Request Closed",
    supportRequestClosedMessage: "Your support request has been closed by the admin team.",
    supportRequestClosedWithReplyMessage: "Your support request has been closed by the admin team. A reply has been sent.",
    supportRequestInProgressTitle: "Support Request In Progress",
    supportRequestInProgressMessage: "Your support request is now in progress. Our team is reviewing your case.",
    myAds: "My Ads",
    myAdsDescription: "Manage your ad requests and active ads.",
    newAdRequest: "New Ad Request",
    noAdRequestsYet: "No ad requests yet.",
    noAdRequestsYetDescription: "You haven't submitted any ad requests yet.",
    adTitle: "Ad Title",
    adImage: "Ad Image",
    uploadImage: "Upload Image",
    changeImage: "Change Image",
    statusPendingReview: "Pending Review",
    statusPendingPayment: "Pending Payment",
    statusPaymentReview: "Payment Review",
    statusActive: "Active",
    statusRejected: "Rejected",
    statusPendingReviewDescription: "Your ad is awaiting review by the admin team.",
    statusPendingPaymentDescription: "Your ad has been approved. Please make the payment to activate it.",
    statusPaymentReviewDescription: "You have uploaded payment proof. The admin is reviewing it.",
    statusActiveDescription: "Your ad is now active and live on the platform.",
    statusRejectedDescription: "Your ad has been rejected by the admin.",
    uploadPaymentProof: "Upload Payment Proof",
    adPaymentConfirmedTitle: "Payment Confirmed",
    adPaymentConfirmedMessage: "Your payment for the ad has been confirmed. The ad is now active!",
    adPaymentRejectedTitle: "Payment Rejected",
    adPaymentRejectedMessage: "Your payment proof was rejected. Please upload a clear image of the payment.",
    adRequestInPaymentReviewMessage: "Your payment proof is under review by the admin team.",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    termsTitle: "Terms of Service",
    termsDescription: "Our terms and conditions for using the platform.",
    termsContent: "This is a placeholder for the terms of service content...",
    privacyTitle: "Privacy Policy",
    privacyDescription: "Our privacy policy on how we handle your data.",
    privacyContent: "This is a placeholder for the privacy policy content...",
    identityVerification: "Identity Verification",
    identityVerificationDescription: "Verify your identity to build trust with users and unlock more features.",
    verificationNotSubmitted: "Not Submitted",
    uploadDocuments: "Upload Documents",
    reUploadDocuments: "Re-upload Documents",
    verificationPendingTitle: "Verification Pending",
    verificationPendingDescription: "Your documents have been submitted and are awaiting admin review.",
    verificationVerifiedTitle: "Verification Verified",
    verificationVerifiedDescription: "Your identity has been successfully verified!",
    verificationRejectedTitle: "Verification Rejected",
    verificationRejectedDescription: "Your identity verification was rejected. Please review the reason and re-upload your documents.",
    verificationDocsUploadedTitle: "Documents Uploaded",
    verificationDocsUploadedDescription: "Your verification documents have been uploaded and are awaiting review.",
    providerVerifications: "Provider Verifications",
    noPendingVerifications: "No pending verifications.",
    noPendingVerificationsDescription: "There are no provider verification requests to review at the moment.",
    approve: "Approve",
    uploadedDocuments: "Uploaded Documents",
    confirmRejectVerificationTitle: "Are you sure you want to reject this verification?",
    confirmRejectVerificationDescription: "This will notify the provider that their verification was rejected.",
    verifiedProvider: "Verified Provider",
    disputeResolution: "Dispute Resolution",
    noDisputes: "No disputes.",
    noDisputesDescription: "There are no disputes to review at the moment.",
    viewDispute: "View Dispute",
    disputeDetails: "Dispute Details",
    disputeTimeline: "Dispute Timeline",
    disputeReason: "Dispute Reason",
    disputeConversation: "Dispute Conversation",
    resolution: "Resolution",
    adminNotes: "Admin Notes",
    sideWithSeeker: "Side with Seeker",
    sideWithProvider: "Side with Provider",
    submitResolution: "Submit Resolution",
    confirmResolutionTitle: "Confirm Resolution",
    confirmResolutionDescription: "Are you sure you want to submit this resolution? This action is irreversible.",
    resolutionSubmitted: "Resolution Submitted",
    failedToSubmitResolution: "Failed to submit resolution. Please try again.",
    disputeResolvedTitle: "Dispute Resolved",
    disputeResolvedSeekerFavorMessage: "The dispute has been resolved in favor of the seeker. The funds will be released to them.",
    disputeResolvedProviderFavorMessage: "The dispute has been resolved in favor of the provider. The funds will be released to them.",
    orderId: "Order ID",
    orderSummary: "Order Summary",
    amount: "Amount",
    disputedOn: "Disputed On",
    sendMessageToParties: "Send a message to both parties involved in the dispute.",
    explainDecision: "Explain your decision and reasoning to both parties.",
    orderCouldNotBeLoaded: "Order details could not be loaded.",
    couldNotLoadMessages: "Messages could not be loaded.",
    resolutionNotesRequired: "Resolution notes are required.",
    failedToFetchDisputeDetails: "Failed to fetch dispute details.",
    orderIdMissing: "Order ID is missing.",
    admin: "Admin",
    unknownUser: "Unknown User",
    partiesInvolved: "Parties Involved",
    messageSeeker: "Message Seeker",
    analyzingBioTitle: "Analyzing Bio",
    analyzingBioDescription: "We are analyzing your bio to suggest a category.",
    categoryAutoDetectedTitle: "Category Auto-Detected",
    categoryAutoDetectedDescription: "We've set your primary category to: {category}. You can change it manually if needed.",
    aiCategorizationUnavailableTitle: "AI Categorization Unavailable",
    aiCategorizationUnavailableDescription: "The AI categorization service is currently unavailable.",
};
